# Usage: export ANSIBLE_TF_DIR=../terraform && ansible-playbook --vault-id ~/.ansible_vault_pass.txt -i /etc/ansible/terraform.py consul_cluster.yml -e 'target_env=staging'
#

- hosts: 'localhost'
  connection: 'local'
  tasks:
  - block:
    - include_role: {name: 'register_inventory_hosts'}
    rescue:
    - fail:
        msg: "Failed to register inventory hosts"

- hosts: 'localhost'
  connection: 'local'
  gather_facts: no
  tasks:
  - block:
    - include_role: {name: 'download_consul'}
    rescue:
    - fail:
        msg: "Failed to download consul to {{ consul_download_dir }}"

- hosts: "!localhost"
  remote_user: "root"
  become: 'yes'
  tasks:
  - block:
    - include_role: {name: 'deploy_consul'}
    rescue:
    - fail:
        msg: "Failed to deploy consul to all nodes (client + servers)"

- hosts: "{{target_env}}:&server"
  remote_user: "root"
  become: 'yes'
  tasks:
  - block:
    - include_role: {name: 'upgrade_node'}
      vars: {node_role: 'server'}
    rescue:
    - fail:
        msg: "Failed to upgrade consul cluster nodes"

- hosts: "{{target_env}}:&client"
  remote_user: "root"
  become: 'yes'
  tasks:
  - block:
    - include_role: {name: 'upgrade_node'}
      vars: {node_role: 'client'}
    - include_role: {name: 'upgrade_ui'}
    rescue:
    - fail:
        msg: "Failed to upgrade consul client + ui"
